@startuml Campground Booking Use Case Diagram

left to right direction

rectangle "Campground Booking" {
  usecase "Register" as register
  usecase "Log In" as login
  usecase "Log Out" as logout
  
  usecase "Add\nBooking" as addBooking
  usecase "Get All\nBookings" as getAllBooking
  usecase "Get\nBooking" as getBooking
  usecase "update\nBooking" as updateBooking
  usecase "delete\nBooking" as deleteBooking

  usecase "Add\nCampground" as addCampground
  usecase "Get All\nCampgrounds" as getAllCampground
  usecase "Get\nCampground" as getCampground
  usecase "update\nCampground" as updateCampground
  usecase "delete\nCampground" as deleteCampground

  usecase "Get Bookmark\nCampgrounds" as getBookmarkCampground
  usecase "Add Bookmark\nCampground" as addBookmarkCampground
  usecase "Delete Bookmark\nCampground" as deleteBookmarkCampground

}

actor "Registered_User" as registered_user 
registered_user -- register
registered_user -- login
registered_user -- logout

registered_user -- addBooking
registered_user -- getAllBooking
registered_user -- getBooking
registered_user -- updateBooking
registered_user -- deleteBooking

registered_user -- getAllCampground
registered_user -- getCampground

registered_user -- getBookmarkCampground
registered_user -- addBookmarkCampground
registered_user -- deleteBookmarkCampground

actor "Admin" as admin
register -- admin
login -- admin
logout -- admin

addBooking -- admin
getAllBooking -- admin
getBooking -- admin
updateBooking -- admin
deleteBooking -- admin

addCampground -- admin
getAllCampground -- admin
getCampground -- admin
updateCampground -- admin
deleteCampground -- admin

getBookmarkCampground -- admin
addBookmarkCampground -- admin
deleteBookmarkCampground -- admin

@enduml